name: Deploy to EC2
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to EC2 by using SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /home/ubuntu/app
          git pull origin master
          docker stop myApp
          docker rm myApp
          cd program
          docker build -t my-app:latest .
          docker run -d --name dfpContainer\
          -p 80:80 \
          -e "HTTP_PORT=:80" \
          -e "MYSQL_ROOT_PASSWORD=12345678" \
          -e "MYSQL_USER=root" \
          -e "MYSQL_PASSWORD=root" \
          -e "MYSQL_DATABASE=alta_shop_project" \
          -e "MYSQL_HOST=13.213.1.38" \
          -e "MYSQL_PORT=3306" \
          my-app:latest
